name: uploadartifact
env:
  WORKFLOWNAME: 'Upload_artifcat'

on: push

jobs:
  upload-artifact:
    name: UploadArtifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Step1
      uses: actions/checkout@v2
    - name: Step2
      run: |
        echo "1. $WORKFLOWNAME"
        echo "2. ${{ env.WORKFLOWNAME" }}
